sp500_ucits_etf:
  ticker: "VUAG.L"
  name: "S&P 500 UCITS ETF - Accumulating (VUAG.L)"
  currency: "GBP"
  ocf: 0.07
  source: "yfinance"
  added: "2025-05-28"

  accumulation: true
  asset_class: "equity"
  region: "US"
  hedged: false
  base_currency: "USD"

  inception_date: "2019-05-14"
  frequency: "daily"

ftse_global_all_cap:
  ticker: "0P00018XAR.L"
  name: "FTSE Global All Cap Index Fund Accumulation"
  currency: "GBP"
  ocf: 0.23
  source: "yfinance"
  added: "2025-05-28"

  accumulation: true
  asset_class: "equity"
  region: "Global"
  hedged: false
  base_currency: "Multi"

  inception_date: "2016-11-08"
  frequency: "daily"

global_short_term_bond:
  ticker: "IE00BH65QG55.IR"
  name: "Global Short-Term Bond Index Fund - Hedged Accumulation"
  currency: "GBP"
  ocf: 0.15
  source: "yfinance"
  added: "2025-05-28"

  accumulation: true
  asset_class: "bond"
  region: "Global"
  hedged: true
  base_currency: "Multi"

  inception_date: "2014-01-31"
  frequency: "daily"

ftse_developed_europe_ex_uk:
  ticker: "GB00BPN5P014.L"
  name: "FTSE Developed Europe ex-U.K. Equity Index Fund - Accumulation"
  currency: "GBP"
  ocf: 0.10
  source: "yfinance"
  added: "2025-05-29"

  accumulation: true
  asset_class: "equity"
  region: "Europe ex-UK"
  hedged: false
  base_currency: "EUR"

  inception_date: "2019-06-23"
  frequency: "daily"